### PR TITLE
change: Deprecate Node.js 16 support

### PR DESCRIPTION
**Pull request by lahirumaramba**
- Deprecate Node.js 16 support
- Add Node.js 18, 20, and 22 to CIs

### CODE REVIEW

**Review by jonathanedey — APPROVED** [review]
LGTM!

**Comment by AlvesJorge** [comment]
@lahirumaramba why was this not a major release? It introduced a breaking change

**Comment by lahirumaramba** [comment]
> @lahirumaramba @jonathanedey why was this not a major release? It introduced a breaking change

It was a deprecation not a breaking change. We did not drop support for Node 16

**Comment by AlvesJorge** [comment]
In the Release where this PR is mentioned it's written as a breaking change

**Comment by lahirumaramba** [comment]
Ah yes, you are right! We highlight important changes in the release notes with the `Changed` tag and use `Breaking change:` for major releases. https://firebase.google.com/support/release-notes/admin/node#version_1220_-_20_june_2024

I see what you mean in the Github release notes though https://github.com/firebase/firebase-admin-node/releases/tag/v12.2.0
Thanks for flagging it. We will keep this in mind for future releases to avoid any confusion.

**Pull request merged**
