### PR TITLE
fix(auth): Make displayName optional for AuthProviderConfig typings

### PR DESCRIPTION
**Pull request by MathBunny**
### Observation
There is a discrepancy regarding `displayName` being a mandatory field in `AuthProviderConfig`.

Source
https://github.com/firebase/firebase-admin-node/blob/031edc2c3eb3b676b95063ce33bfc5673d7dc2bc/src/auth/auth-config.ts#L29-L34

Typings
https://github.com/firebase/firebase-admin-node/blob/031edc2c3eb3b676b95063ce33bfc5673d7dc2bc/src/auth.d.ts#L1062-L1082

### Solution

Assuming the typings are the source of truth I made it a mandatory field.

### CODE REVIEW

**Comment by hiranya911** [comment]
This might be a case of `AuthProviderConfig` type internally used for create/update requests as well. If not, LGTM.

**Comment by MathBunny** [comment]
That's true ... thinking out loud, in that case I could set the `displayName` attribute of `AuthProviderConfig` to `string | undefined` and then in sub-classes such as `SAMLConfig` to `string`, maybe that would work?

**Comment by bojeil-google** [comment]
I think this was a mistake. `displayName` is not required on a provider. It is definitely not required for update requests.

**Comment by MathBunny** [comment]
Do you suggest I change the `d.ts` file then, and wait for a major version change? Or leave it as is?

**Comment by hiranya911** [comment]
If the displayName is allowed to be `undefined` on some of the objects, then our current typings are incorrect. It should be corrected and the change can be treated as a bug fix.

**Comment by bojeil-google** [comment]
Yeah, that would be great. I think we should update it in the typings to be optional. Thank you.

**Comment by MathBunny** [comment]
Thanks for the responses, @bojeil-google PTAL :)

**Comment by bojeil-google** [comment]
I already approved :)

**Pull request merged**
