### PR TITLE
fix: Use optional chaining in FirebaseError

### PR DESCRIPTION
**Pull request by lahirumaramba**
Fixes: #2571

### CODE REVIEW

**Review by jonathanedey — APPROVED** [review]
LGTM!

**Comment by Nushio** [comment]
Thanks for the quick turnaround on this. It fixes the test issues in our project!

**Comment by jbaldassari** [comment]
Confirmed this fixes my project as well

**Comment by lahirumaramba** [comment]
@Nushio @jbaldassari Thanks for confirming the fix!

**Pull request merged**
