### PR TITLE
issue 2467: add async to send each loop to prevent local validation f…

### PR DESCRIPTION
**Pull request by DyosTheNerd**
### Discussion
adds async to send each loop to prevent local validation from throwing errors which could result in messages being sent and accepted by the api, while the function would still throw an error.

### Testing

adds a test with a successful message and one that does not pass local validation. Previously, this would throw an error.

### CODE REVIEW

**Review by Doris-Ge — APPROVED** [review]
Thank you for adding this!

**Review by jonathanedey — APPROVED** [review]
LGTM! Thank you @DyosTheNerd for the contribution.

**Comment by DyosTheNerd** [comment]
no probs :) @jonathanedey as branch is out of date, do you need me to update the branch, or will it automatically be done on merge from your side?

**Comment by jonathanedey** [comment]
Yes could you update the branch. Updating on your side makes it easier in case there are any conflicts. Thanks!

**Pull request merged**
